sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm run prebuild
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage