version: 2
jobs:
  build:

    docker:
      - image: circleci/node:9-browsers

    steps:
      - run:
          name: Set git config
          command: |
            git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
            git config --global user.name "$GH_NAME" > /dev/null 2>&1

      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: npm install

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Send coverage report to codacy
          command: cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
      
      - run:
          name: Deploy API docs to github pages
          command: npm run docs
          filters:
            branches:
              only: develop

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules