version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
      - restore_cache:
        keys:
          - dependency-cache-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - node_modules
      - run: npm run build