version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
      - run: npm i
      - run: npm i -g npx
      - run: npm run prebuild
      - run: cat ./coverage/lcov.info | npx codacy-coverage